### ISSUE TITLE
`npm test` not work

### ISSUE THREAD

**Issue by iulo** [jonschlinkert/template#35]
```
/Users/xxx/learn/tem/node_modules/template/node_modules/mocha/lib/utils.js:628
        throw new Error("cannot resolve path (or pattern) '" + path + "'");
        ^

Error: cannot resolve path (or pattern) 'test'
    at Object.lookupFiles (/Users/xxx/learn/tem/node_modules/template/node_modules/mocha/lib/utils.js:628:15)
    at /Users/xxx/learn/tem/node_modules/template/node_modules/mocha/bin/_mocha:326:30
    at Array.forEach (native)
    at Object.<anonymous> (/Users/xxx/learn/tem/node_modules/template/node_modules/mocha/bin/_mocha:325:6)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
    at node.js:963:3
```

**Comment by iulo** [comment]
worked now
